feat(workload) create catalogue item
stax-labs/lib-stax-python-sdk pull request #17
Opened 2020-05-05 04:56 UTC by ZXYmania

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

2020-05-07 22:20 UTC, mat-lord requested changes
We've tried to mirror the API routes as example directories, hence there is no route `workload_catalogue_version`. Can you please move the `workload_catalogue_version` files (keep the same file name) into the `workload_catalogue` directory?

2020-05-08 00:00 UTC, ZXYmania commented on examples/workload_catalogue/delete_catalogue_item.py
> +client = StaxClient("workloads")
ok will change this one to workload client.

2020-05-08 00:03 UTC, ZXYmania commented
> We've tried to mirror the API routes as example directories, hence there is no route `workload_catalogue_version`. Can you please move the `workload_catalogue_version` files (keep the same file name) into the `workload_catalogue` directory?

Instead will move them all into the workloads folder to replicate the structure of the sdk

2020-05-08 05:48 UTC, mat-lord approved these changes

2020-05-08 05:56 UTC, merged